=== RosiePuddles/Year2Project/Server/data/dtds/session.dtd
<!ELEMENT session (time, hr_data, gaze_data)>
<!ATTLIST session id CDATA #REQUIRED>
<!ELEMENT hr_data (hr_element*)>
<!ELEMENT hr_element (time, pulse)>
<!ELEMENT gaze_data (gaze_element*)>
<!ELEMENT gaze_element (time, yaw, pitch)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT pulse (#PCDATA)>
<!ELEMENT yaw (#PCDATA)>
<!ELEMENT pitch (#PCDATA)>

=== RosiePuddles/Year2Project/Server/data/000/001.xml
<?xml version="1.0" encoding="UTF-8" ?><!DOCTYPE session SYSTEM "../dtds/session.dtd"><session id="0"><time>1671080669</time><hr_data><hr_element><time>1671080702</time><pulse>40</pulse></hr_element><hr_element><time>1671080712</time><pulse>35</pulse></hr_element></hr_data><gaze_data><gaze_element><time>1671080702</time><yaw>0</yaw><pitch>-3.9</pitch></gaze_element><gaze_element><time>1671080707</time><yaw>12</yaw><pitch>55</pitch></gaze_element></gaze_data></session>
